palette = "catppuccin_mocha"
[battery]
full_symbol = " 🔋"
charging_symbol = " 🔌"
disabled = true
discharging_symbol = " ⚡"

[[battery.display]]
threshold = 100 
style = "bold red"

[character]
error_symbol = " [✖](bold red) "
success_symbol = " [➤](bold red)"

[directory]
truncation_length = 5
style = "bold italic white"
format = "[in](bold red) [$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
format = "[on](bold red) [$symbol$branch]($style) "
symbol = ' '
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"


[hostname]
ssh_only = false
format = "[$hostname]($style) "
trim_at = "-"
style = "bold dimmed green"
disabled =false 

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )]($style)[(\($virtualenv\) )](bold red)'
style = "blue"

[rust]
format = "[$symbol$version]($style) "
style = "bold green"

[username]
format = " [$user]($style)@"
style_user = "bold dimmed blue"
show_always = true

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
